apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-deployment
  annotations:
    policy.open-cluster-management.io/standards: NIST 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-spring-deployment
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            include:
              - demo
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: spring-deployment
                  labels:
                    app: spring
                spec:
                  replicas: 3
                  selector:
                    matchLabels:
                      app: spring
                  template:
                    metadata:
                      labels:
                        app: spring
                    spec:
                      containers:
                        - name: spring
                          image: 'quay.io/rpuccini/spring-music'
                          ports:
                            - containerPort: 80
